[package]
name = "paladin-gtk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "GTK4/libadwaita desktop front-end for paladin"

[lints]
workspace = true

[dependencies]
adw = { version = "0.9", package = "libadwaita", features = ["v1_5"] }
anyhow = "1.0.102"
gtk = { version = "0.11", package = "gtk4", features = ["v4_10"] }
relm4 = { version = "0.11.0", features = ["libadwaita"] }
relm4-components = "0.11.0"
paladin-core = { version = "0.1.0", path = "../paladin-core" }
tempfile = "3.27.0"
zeroize = "1.8.2"
